# Site set
baseurl: "http://darthseniorcondomoradadosol.github.io" # the subpath of your site, e.g. /blog/
url: "http://darthseniorcondomoradadosol.github.io" # the base hostname & protocol for your site

# User setting
owner: Condomínio Morada do Sol	
email: contato@condomoradadosol.com.br
facebook_username:
twitter_username:
github_username:
address: Rua Santo Antônio 206, Nova Iguaçu
  # Feel free to add more lines here 
telephone: 21 99664-2226 e 21 97048-0593
copyright:

# API settings
google_api_key: AIzaSyDaNM-wPQ-f8bMmoqKzuvx6Sd_WhiNxX98

# Build settings
markdown: kramdown